version: '3'

services:
  # MySQL service
  db:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    ports:
      - "3307:3306"

  # PHP and Apache service
  web:
    image: php:apache
    container_name: php-apache-container
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./html:/var/www/html
    ports:
      - "81:80"
    links:
      - db

  # phpMyAdmin service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "8082:80"
